# Generated by Django 4.1.7 on 2023-05-25 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_alter_donations_pay_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate_80g',
            name='created_date',
            field=models.DateTimeField(default='2023-03-10 00:00:00'),
        ),
    ]
