# Generated by Django 4.1.7 on 2023-05-26 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_donations_donation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donations',
            name='donation_date',
            field=models.DateField(null=True),
        ),
    ]
