# Generated by Django 4.1.7 on 2023-05-26 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_alter_feature_campaigns_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature_campaigns',
            name='image',
            field=models.ImageField(upload_to='hhc/hhc/static/account/image/featured/'),
        ),
    ]
